[package]
name = "rustycli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "rustycli"
path = "src/main.rs"

[dependencies]
rustycli-core = { path = "../rustycli-core" }
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true

