[package]
name = "devcli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "devcli"
path = "src/lib.rs"

[[bin]]
name = "devcli"
path = "src/main.rs"

[dependencies]
devcli-core = { path = "../devcli-core" }
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true

